[package]
name = "chabeau"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossterm = "0.29"
ratatui = "0.29"
clap = { version = "4.0", features = ["derive"] }
futures-util = "0.3"
